baseURL = "https://sensical.es/"
locale = "en-us"
title = "Sensical SCCL"

[module]
  [module.hugoVersion]
    extended = true
    min = "0.92.0"

[params]
  google_analytics_id=""

  [params.logo]
    mobile = "images/logo-mobile.svg"
    mobile_height = "36px"
    mobile_width = "36px"
    desktop = "images/sensical-logo.png"
    desktop_height = "29px"
    desktop_width = "217px"
    text = "snscl"
    alt = "Sensical SCCL"

  [params.homepage_meta_tags]
    meta_description = "Sensical SCCL is amultidisciplinary group of developers, creatives, and researchers passionate about open technology, sustainability, prototyping, and science."
    meta_og_title = "Sensical SCCL"
    meta_og_type = "website"
    meta_og_url = "https://sensical.es/"
    meta_og_image = "images/sensical-logo.png"
    meta_og_description = "Sensical SCCL is amultidisciplinary group of developers, creatives, and researchers passionate about open technology, sustainability, prototyping, and science."

[[menu.main]]
  name = "Work"
  url = "/work/"
  weight = 2

[[menu.main]]
  name = "About"
  url = "/about/"
  weight = 3

[[menu.main]]
  name = "Contact"
  url = "/contact/"
  weight = 4

[permalinks]
  post = "/:year/:month/:day/:slug/"
  pages = "/:contentbasename/"

[languages]
  [languages.en]
    contentDir = 'content/en'
    label = 'en'
    weight = 10
    [languages.en.menus]
      [[languages.en.menus.main]]
        name = 'Work'
        pageRef = '/work'
        weight = 10
      [[languages.en.menus.main]]
        name = 'About'
        pageRef = '/pages/about'
        weight = 20
      [[languages.en.menus.main]]
        name = 'Contact'
        pageRef = '/contact'
        weight = 30